apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-minikube:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-minikube:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: golang-http-minikube
        chartPath: charts/golang-http-minikube
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/davidcurrie/golang-http-minikube"
          image.tag: "{{.DIGEST_HEX}}"
        
